# Generated by Django 5.0.6 on 2024-07-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Blog/image')),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
